version: '3'
services:
  keras-gpu-jupyter:
    build:
      context: ./
      dockerfile: ../../docker/Dockerfile.keras-gpu-py37
    runtime: nvidia
    volumes:
      - ".:/tf/notebooks"
      - "../cqp:/tf/cqp"
    ports:
      - "8888:8888"
