FROM tensorflow/tensorflow:latest-gpu-jupyter

COPY requirements.txt .

RUN apt-get update && \
    apt-get install --no-install-recommends -y \
    python3.7 && \
    rm -rf /var/lib/apt/lists/* && \
    ln -sf /usr/bin/python3.7 /usr/bin/python3 && \
    python3 -m pip install --upgrade pip && \
    pip3 install -r requirements.txt && \
    pip3 install tensorflow
