image_params:
  - topic: "/carla/ego_vehicle/camera/rgb/front/image_color"
    bitrate: 1000
    skip_frames: 0
    width: 640
    height: 480
    chroma_drop: false
    filter:
      type: "none"
      ksize: 1
      sigma: 0.0
  - topic: "/carla/ego_vehicle/camera/rgb/front_left/image_color"
    bitrate: 1000
    skip_frames: 0
    width: 640
    height: 480
    chroma_drop: false
    filter:
      type: "none"
      ksize: 1
      sigma: 0.0
  - topic: "/carla/ego_vehicle/camera/rgb/front_right/image_color"
    bitrate: 1000
    skip_frames: 0
    width: 640
    height: 480
    chroma_drop: false
    filter:
      type: "none"
      ksize: 1
      sigma: 0.0
  - topic: "/carla/ego_vehicle/camera/rgb/rear/image_color"
    bitrate: 1000
    skip_frames: 1
    width: 640
    height: 480
    chroma_drop: false
    filter:
      type: "none"
      ksize: 1
      sigma: 0.0
  - topic: "/carla/ego_vehicle/camera/rgb/rear_left/image_color"
    bitrate: 1000
    skip_frames: 1
    width: 640
    height: 480
    chroma_drop: false
    filter:
      type: "none"
      ksize: 1
      sigma: 0.0
  - topic: "/carla/ego_vehicle/camera/rgb/rear_right/image_color"
    bitrate: 1000
    skip_frames: 2
    width: 320
    height: 240
    chroma_drop: false
    filter:
      type: "none"
      ksize: 1
      sigma: 0.0
