name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  check:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        sudo snap install shfmt
        sudo apt update && sudo apt install clang-format
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Check
      run: |
        pre-commit run --all-files
        make check

  ros:
    runs-on: ubuntu-latest
    container:
      image: ros:noetic-robot
      env:
        DEBIAN_FRONTEND: "noninteractive"
    steps:
    - uses: actions/checkout@v2
    - name: Setup
      shell: bash
      run: |
        sudo apt-get update
        sudo apt-get install -y python3-catkin-tools clang-tidy-10
        $GITHUB_WORKSPACE/script/install.sh
    - name: Init Workspace
      run: |
        mkdir -p $GITHUB_WORKSPACE/../catkin_ws/src
        cd $GITHUB_WORKSPACE/../catkin_ws/src
        ln -s $GITHUB_WORKSPACE driver-awareness
        ln -s $GITHUB_WORKSPACE/../telecarla_manual_control telecarla_manual_control
        ln -s $GITHUB_WORKSPACE/../ros-bridge ros-bridge
        cd ..
        catkin init
    - name: Build and Check
      shell: bash
      run: |
        source /opt/ros/noetic/setup.bash
        cd $GITHUB_WORKSPACE/../catkin_ws
        catkin build --summarize --no-status --force-color --cmake-args -DCMAKE_EXPORT_COMPILE_COMMANDS=ON -DCMAKE_CXX_CLANG_TIDY=clang-tidy-10
    - name: Test
      shell: bash
      run: |
        source /opt/ros/noetic/setup.bash
        cd $GITHUB_WORKSPACE/../catkin_ws
        catkin run_tests --no-status --force-color && catkin_test_results
